name: Node.js CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        run: npm install --save-dev nodemon
        run: npm install --save express
        run: npm install --save mongodb
        run: npm install --save mongoose
        run: npm install --save dotenv
        run: npm install nodemailer
        run: npm install nodemailer crypto
        run: npm install --save nodemailer nodemailer-sendgrid-transport

      - name: Build project
        run: npm run build